{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6e273468-5db8-4ca1-9937-569d1fd08f26",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import re\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "from scipy.io import loadmat\n",
    "\n",
    "# =====================================\n",
    "# 1. CONFIGURATION\n",
    "# =====================================\n",
    "\n",
    "# NOTE:\n",
    "# This pipeline expects user-provided .mat files in DATA_DIR.\n",
    "# Input data are not included in the repository for privacy/research reasons.\n",
    "DATA_DIR = \"data\"\n",
    "\n",
    "OUTPUT_DIR = os.path.join(DATA_DIR, \"output_pipeline_v8\")\n",
    "FIGURES_INDIVIDUAL_PATH = os.path.join(OUTPUT_DIR, \"figures_individual\")\n",
    "FIGURES_SUMMARY_PATH = os.path.join(OUTPUT_DIR, \"figures_summary\")\n",
    "\n",
    "os.makedirs(OUTPUT_DIR, exist_ok=True)\n",
    "os.makedirs(FIGURES_INDIVIDUAL_PATH, exist_ok=True)\n",
    "os.makedirs(FIGURES_SUMMARY_PATH, exist_ok=True)\n",
    "\n",
    "# Analysis convention\n",
    "# baseline: -20 to 0 s relative to task onset\n",
    "# task window: 0 to 60 s relative to task onset\n",
    "BASELINE_WINDOW = (-20, 0)\n",
    "ANALYSIS_WINDOW = (0, 60)\n",
    "MIN_RESPONSE_WINDOW_S = 30  # minimum acceptable segment duration\n",
    "\n",
    "\n",
    "# =====================================\n",
    "# 2. HELPER FUNCTIONS\n",
    "# =====================================\n",
    "\n",
    "def normalize_channel_name(name):\n",
    "    \"\"\"Standardize channel names for robust matching.\"\"\"\n",
    "    name = str(name).strip().lower()\n",
    "    name = re.sub(r\"\\s+\", \" \", name)\n",
    "    return name\n",
    "\n",
    "\n",
    "def normalize_text(text):\n",
    "    \"\"\"Normalize generic text fields.\"\"\"\n",
    "    return str(text).strip().lower()\n",
    "\n",
    "\n",
    "def clean_filename(name):\n",
    "    \"\"\"Remove file extension and replace invalid characters.\"\"\"\n",
    "    name = str(name)\n",
    "    name = name.replace(\".mat\", \"\")\n",
    "    name = re.sub(r\"[^A-Za-z0-9_\\-]+\", \"_\", name)\n",
    "    return name\n",
    "\n",
    "\n",
    "def extract_metadata(filename):\n",
    "    \"\"\"\n",
    "    Extract group, posture, and task information from the filename.\n",
    "\n",
    "    Outputs:\n",
    "        group: CTRL / DP / NA\n",
    "        posture: supine / orthostatic / NA\n",
    "        task: active / passive / NA\n",
    "    \"\"\"\n",
    "    name = filename.lower()\n",
    "\n",
    "    if \"ctrl\" in name or \"controle\" in name:\n",
    "        group = \"CTRL\"\n",
    "    elif \"pd\" in name or \"dp\" in name or \"parkinson\" in name:\n",
    "        group = \"DP\"\n",
    "    else:\n",
    "        group = \"NA\"\n",
    "\n",
    "    if \"supino\" in name or \"supine\" in name:\n",
    "        posture = \"supine\"\n",
    "    elif (\n",
    "        \"ort\" in name\n",
    "        or \"orto\" in name\n",
    "        or \"ortostat\" in name\n",
    "        or \"empe\" in name\n",
    "        or \"em_pe\" in name\n",
    "        or \"standing\" in name\n",
    "        or \"upright\" in name\n",
    "    ):\n",
    "        posture = \"orthostatic\"\n",
    "    else:\n",
    "        posture = \"NA\"\n",
    "\n",
    "    if \"ativo\" in name or \"active\" in name:\n",
    "        task = \"active\"\n",
    "    elif \"passivo\" in name or \"passive\" in name:\n",
    "        task = \"passive\"\n",
    "    else:\n",
    "        task = \"NA\"\n",
    "\n",
    "    return group, posture, task\n",
    "\n",
    "\n",
    "def mean_per_second(signal, time):\n",
    "    \"\"\"Compute per-second mean values from a continuous signal.\"\"\"\n",
    "    duration = int(np.floor(time[-1]))\n",
    "    means = []\n",
    "    times = []\n",
    "\n",
    "    for second in range(duration + 1):\n",
    "        idx = (time >= second) & (time < second + 1)\n",
    "        if np.any(idx):\n",
    "            means.append(np.mean(signal[idx]))\n",
    "            times.append(second)\n",
    "\n",
    "    return np.array(times), np.array(means)\n",
    "\n",
    "\n",
    "def mean_in_window(df, col, t0, t1):\n",
    "    \"\"\"Compute the mean value of a dataframe column within a time window.\"\"\"\n",
    "    x = df.loc[(df[\"t\"] >= t0) & (df[\"t\"] < t1), col].dropna()\n",
    "    return float(x.mean()) if len(x) else np.nan\n",
    "\n",
    "\n",
    "def percent_of_baseline(df, var):\n",
    "    \"\"\"Express a variable as percentage of its baseline mean.\"\"\"\n",
    "    baseline = mean_in_window(df, var, *BASELINE_WINDOW)\n",
    "    if np.isnan(baseline) or baseline == 0:\n",
    "        return pd.Series(np.nan, index=df.index)\n",
    "    return (df[var] / baseline) * 100\n",
    "\n",
    "\n",
    "def find_channel_by_name(titles, candidates):\n",
    "    \"\"\"\n",
    "    Find channel index by matching candidate names against available titles.\n",
    "\n",
    "    Matching strategy:\n",
    "    1. exact match\n",
    "    2. partial match\n",
    "    \"\"\"\n",
    "    normalized_titles = [normalize_channel_name(t) for t in titles]\n",
    "    normalized_candidates = [normalize_channel_name(c) for c in candidates]\n",
    "\n",
    "    for i, title in enumerate(normalized_titles):\n",
    "        if title in normalized_candidates:\n",
    "            return i\n",
    "\n",
    "    for i, title in enumerate(normalized_titles):\n",
    "        for candidate in normalized_candidates:\n",
    "            if candidate in title:\n",
    "                return i\n",
    "\n",
    "    return None\n",
    "\n",
    "\n",
    "# =====================================\n",
    "# 3. ROBUST .MAT FILE LOADING (LABCHART)\n",
    "# =====================================\n",
    "\n",
    "def load_labchart_mat(file_path):\n",
    "    \"\"\"\n",
    "    Load LabChart .mat file and detect its structure format.\n",
    "\n",
    "    Supported formats:\n",
    "    - simple\n",
    "    - block (data_block1)\n",
    "\n",
    "    Returns:\n",
    "        dict with standardized structure\n",
    "    \"\"\"\n",
    "    mat = loadmat(file_path, squeeze_me=True, struct_as_record=False)\n",
    "\n",
    "    # ===== FORMAT 1: SIMPLE =====\n",
    "    if all(k in mat for k in [\"data\", \"titles\", \"datastart\", \"dataend\", \"samplerate\"]):\n",
    "        return {\n",
    "            \"type\": \"simple\",\n",
    "            \"mat\": mat,\n",
    "            \"data\": mat[\"data\"],\n",
    "            \"titles\": np.atleast_1d(mat[\"titles\"]),\n",
    "            \"datastart\": np.atleast_1d(mat[\"datastart\"]),\n",
    "            \"dataend\": np.atleast_1d(mat[\"dataend\"]),\n",
    "            \"samplerate\": np.atleast_1d(mat[\"samplerate\"]),\n",
    "        }\n",
    "\n",
    "    # ===== FORMAT 2: BLOCK =====\n",
    "    if all(k in mat for k in [\"data_block1\", \"titles_block1\", \"ticktimes_block1\"]):\n",
    "        return {\n",
    "            \"type\": \"block\",\n",
    "            \"mat\": mat,\n",
    "            \"data_block\": np.asarray(mat[\"data_block1\"], dtype=float),\n",
    "            \"titles_block\": np.atleast_1d(mat[\"titles_block1\"]),\n",
    "            \"ticktimes_block\": np.atleast_1d(mat[\"ticktimes_block1\"]),\n",
    "            \"comtext_block1\": mat.get(\"comtext_block1\", None),\n",
    "            \"comtick_block1\": mat.get(\"comtick_block1\", None),\n",
    "            \"comchan_block1\": mat.get(\"comchan_block1\", None),\n",
    "        }\n",
    "\n",
    "    raise ValueError(f\"Unrecognized .mat format. Available keys: {sorted(mat.keys())}\")\n",
    "\n",
    "\n",
    "def extract_labchart_channels(file_path):\n",
    "    \"\"\"\n",
    "    Extract MCAv, MAP, and HR channels from LabChart .mat file.\n",
    "    Works for both simple and block formats.\n",
    "    \"\"\"\n",
    "    info = load_labchart_mat(file_path)\n",
    "    mat = info[\"mat\"]\n",
    "\n",
    "    # ========= SIMPLE FORMAT =========\n",
    "    if info[\"type\"] == \"simple\":\n",
    "        data = info[\"data\"]\n",
    "        titles = info[\"titles\"]\n",
    "        datastart = info[\"datastart\"]\n",
    "        dataend = info[\"dataend\"]\n",
    "        samplerate = info[\"samplerate\"]\n",
    "\n",
    "        idx_mcav = find_channel_by_name(\n",
    "            titles, [\"MCAv\", \"MCAv E\", \"MCAV\", \"MCAV E\", \"MCAv1\", \"MCAv 1\"]\n",
    "        )\n",
    "        idx_hr = find_channel_by_name(\n",
    "            titles, [\"FC\", \"Heart Rate\", \"HR\"]\n",
    "        )\n",
    "        idx_map = find_channel_by_name(\n",
    "            titles, [\"MAP\", \"Mean Arterial\", \"Mean Arterial Pressure\", \"PAM\"]\n",
    "        )\n",
    "\n",
    "        if idx_mcav is None:\n",
    "            raise ValueError(\"MCAv channel not found.\")\n",
    "        if idx_hr is None:\n",
    "            raise ValueError(\"HR channel not found.\")\n",
    "        if idx_map is None:\n",
    "            raise ValueError(\"MAP channel not found.\")\n",
    "\n",
    "        def get_channel_simple(i):\n",
    "            start = int(datastart[i]) - 1\n",
    "            end = int(dataend[i])\n",
    "            y = np.asarray(data[start:end], dtype=float)\n",
    "            fs = float(samplerate[i])\n",
    "            name = str(titles[i]).strip()\n",
    "            return {\"name\": name, \"y\": y, \"fs\": fs}\n",
    "\n",
    "        channels = {\n",
    "            \"mcav\": get_channel_simple(idx_mcav),\n",
    "            \"hr\": get_channel_simple(idx_hr),\n",
    "            \"map\": get_channel_simple(idx_map),\n",
    "        }\n",
    "\n",
    "        return mat, channels, info\n",
    "\n",
    "    # ========= BLOCK FORMAT =========\n",
    "    elif info[\"type\"] == \"block\":\n",
    "        data_block = np.asarray(info[\"data_block\"], dtype=float)\n",
    "        titles_block = np.atleast_1d(info[\"titles_block\"])\n",
    "        ticktimes_block = np.asarray(info[\"ticktimes_block\"], dtype=float).squeeze()\n",
    "        t = np.ravel(ticktimes_block)\n",
    "\n",
    "        if data_block.ndim == 1:\n",
    "            data_block = data_block[:, None]\n",
    "\n",
    "        if data_block.shape[0] == len(titles_block) and data_block.shape[1] == len(t):\n",
    "            data_block = data_block.T\n",
    "        elif data_block.shape[1] == len(titles_block) and data_block.shape[0] == len(t):\n",
    "            pass\n",
    "        elif data_block.shape[0] == len(titles_block):\n",
    "            data_block = data_block.T\n",
    "        elif data_block.shape[1] == len(titles_block):\n",
    "            pass\n",
    "        else:\n",
    "            raise ValueError(\n",
    "                f\"Unexpected block format: data_block shape={data_block.shape}, \"\n",
    "                f\"n_titles={len(titles_block)}, n_ticks={len(t)}\"\n",
    "            )\n",
    "\n",
    "        idx_mcav = find_channel_by_name(\n",
    "            titles_block, [\"MCAv\", \"MCAv E\", \"MCAV\", \"MCAV E\", \"MCAv1\", \"MCAv 1\"]\n",
    "        )\n",
    "        idx_hr = find_channel_by_name(\n",
    "            titles_block, [\"FC\", \"Heart Rate\", \"HR\"]\n",
    "        )\n",
    "        idx_map = find_channel_by_name(\n",
    "            titles_block, [\"MAP\", \"Mean Arterial\", \"Mean Arterial Pressure\", \"PAM\"]\n",
    "        )\n",
    "\n",
    "        if idx_mcav is None:\n",
    "            raise ValueError(\"MCAv channel not found (block).\")\n",
    "        if idx_hr is None:\n",
    "            raise ValueError(\"HR channel not found (block).\")\n",
    "        if idx_map is None:\n",
    "            raise ValueError(\"MAP channel not found (block).\")\n",
    "\n",
    "        def get_channel_block(i):\n",
    "            y = np.asarray(data_block[:, i], dtype=float)\n",
    "            name = str(titles_block[i]).strip()\n",
    "\n",
    "            dt = np.diff(t)\n",
    "            dt = dt[np.isfinite(dt)]\n",
    "            dt = dt[dt > 0]\n",
    "\n",
    "            if len(dt) == 0:\n",
    "                raise ValueError(f\"Could not estimate sampling rate for channel {name}.\")\n",
    "\n",
    "            fs = 1.0 / np.median(dt)\n",
    "            return {\"name\": name, \"y\": y, \"fs\": fs, \"t\": t}\n",
    "\n",
    "        channels = {\n",
    "            \"mcav\": get_channel_block(idx_mcav),\n",
    "            \"hr\": get_channel_block(idx_hr),\n",
    "            \"map\": get_channel_block(idx_map),\n",
    "        }\n",
    "\n",
    "        return mat, channels, info\n",
    "\n",
    "\n",
    "def inspect_mat_file(file_path):\n",
    "    \"\"\"\n",
    "    Print diagnostic information about .mat file structure.\n",
    "    Useful for debugging unknown formats.\n",
    "    \"\"\"\n",
    "    mat = loadmat(file_path, squeeze_me=True, struct_as_record=False)\n",
    "\n",
    "    print(\"Available keys:\")\n",
    "    print(sorted(mat.keys()))\n",
    "\n",
    "    if \"titles\" in mat:\n",
    "        print(\"\\nChannel titles:\")\n",
    "        for i, t in enumerate(np.atleast_1d(mat[\"titles\"])):\n",
    "            print(i, str(t))\n",
    "\n",
    "    if \"titles_block1\" in mat:\n",
    "        print(\"\\nChannel titles (block1):\")\n",
    "        for i, t in enumerate(np.atleast_1d(mat[\"titles_block1\"])):\n",
    "            print(i, str(t))\n",
    "\n",
    "\n",
    "# =====================================\n",
    "# 4. EVENTS / TASK MARKERS\n",
    "# =====================================\n",
    "\n",
    "def extract_comments(mat):\n",
    "    \"\"\"\n",
    "    Extract event/comment markers from LabChart .mat structures.\n",
    "\n",
    "    Returns a sorted list of tuples: (time, text)\n",
    "    \"\"\"\n",
    "    comments = []\n",
    "\n",
    "    possible_pairs = [\n",
    "        (\"comtime\", \"comtext\"),\n",
    "        (\"commenttime\", \"commenttext\"),\n",
    "        (\"eventtime\", \"eventtext\"),\n",
    "    ]\n",
    "\n",
    "    for time_key, text_key in possible_pairs:\n",
    "        if time_key in mat and text_key in mat:\n",
    "            times = np.atleast_1d(mat[time_key])\n",
    "            texts = np.atleast_1d(mat[text_key])\n",
    "\n",
    "            n = min(len(times), len(texts))\n",
    "            for i in range(n):\n",
    "                try:\n",
    "                    t = float(times[i])\n",
    "                    txt = normalize_text(texts[i])\n",
    "                    comments.append((t, txt))\n",
    "                except Exception:\n",
    "                    pass\n",
    "\n",
    "    if \"comtick_block1\" in mat and \"comtext_block1\" in mat and \"ticktimes_block1\" in mat:\n",
    "        comtick = np.atleast_1d(mat[\"comtick_block1\"])\n",
    "        comtext = np.atleast_1d(mat[\"comtext_block1\"])\n",
    "        ticktimes = np.atleast_1d(mat[\"ticktimes_block1\"]).squeeze()\n",
    "        ticktimes = np.ravel(ticktimes)\n",
    "\n",
    "        n = min(len(comtick), len(comtext))\n",
    "        for i in range(n):\n",
    "            try:\n",
    "                idx = int(comtick[i]) - 1\n",
    "                if 0 <= idx < len(ticktimes):\n",
    "                    t = float(ticktimes[idx])\n",
    "                    txt = normalize_text(comtext[i])\n",
    "                    comments.append((t, txt))\n",
    "            except Exception:\n",
    "                pass\n",
    "\n",
    "    comments = sorted(comments, key=lambda x: x[0])\n",
    "    return comments\n",
    "\n",
    "\n",
    "def find_task_window_from_comments(mat, expected_task):\n",
    "    \"\"\"\n",
    "    Determine task start and end times based on event comments.\n",
    "    \"\"\"\n",
    "    comments = extract_comments(mat)\n",
    "    expected_task = normalize_text(expected_task)\n",
    "\n",
    "    task_comments = [(t, txt) for t, txt in comments if txt == expected_task]\n",
    "\n",
    "    if len(task_comments) >= 2:\n",
    "        start_time_abs = task_comments[0][0]\n",
    "        end_time_abs = task_comments[1][0]\n",
    "        source = \"comments\"\n",
    "        return start_time_abs, end_time_abs, comments, source\n",
    "\n",
    "    elif len(task_comments) == 1:\n",
    "        start_time_abs = task_comments[0][0]\n",
    "        end_time_abs = start_time_abs + 60.0\n",
    "        source = \"single_comment\"\n",
    "        return start_time_abs, end_time_abs, comments, source\n",
    "\n",
    "    else:\n",
    "        start_time_abs = 20.0\n",
    "        end_time_abs = 80.0\n",
    "        source = \"fallback_20_80\"\n",
    "        return start_time_abs, end_time_abs, comments, source\n",
    "\n",
    "\n",
    "# =====================================\n",
    "# 5. PROCESS A SINGLE .MAT FILE\n",
    "# =====================================\n",
    "\n",
    "def process_mat_file(file_path, expected_task):\n",
    "    \"\"\"\n",
    "    Process a single LabChart .mat file and compute key physiological metrics.\n",
    "    \"\"\"\n",
    "    mat, channels, info = extract_labchart_channels(file_path)\n",
    "\n",
    "    mcav = channels[\"mcav\"][\"y\"]\n",
    "    hr = channels[\"hr\"][\"y\"]\n",
    "    map_signal = channels[\"map\"][\"y\"]\n",
    "\n",
    "    if info[\"type\"] == \"block\":\n",
    "        t_mcav_abs = np.asarray(channels[\"mcav\"][\"t\"], dtype=float)\n",
    "        t_hr_abs = np.asarray(channels[\"hr\"][\"t\"], dtype=float)\n",
    "        t_map_abs = np.asarray(channels[\"map\"][\"t\"], dtype=float)\n",
    "    else:\n",
    "        t_mcav_abs = np.arange(len(mcav)) / channels[\"mcav\"][\"fs\"]\n",
    "        t_hr_abs = np.arange(len(hr)) / channels[\"hr\"][\"fs\"]\n",
    "        t_map_abs = np.arange(len(map_signal)) / channels[\"map\"][\"fs\"]\n",
    "\n",
    "    t_mcav_1hz_abs, mcav_1hz = mean_per_second(mcav, t_mcav_abs)\n",
    "    t_hr_1hz_abs, hr_1hz = mean_per_second(hr, t_hr_abs)\n",
    "    t_map_1hz_abs, map_1hz = mean_per_second(map_signal, t_map_abs)\n",
    "\n",
    "    start_time_abs, end_time_abs, comments, window_source = find_task_window_from_comments(\n",
    "        mat, expected_task\n",
    "    )\n",
    "\n",
    "    t_mcav_rel = t_mcav_1hz_abs - start_time_abs\n",
    "    t_hr_rel = t_hr_1hz_abs - start_time_abs\n",
    "    t_map_rel = t_map_1hz_abs - start_time_abs\n",
    "\n",
    "    hr_1hz_aligned = np.interp(t_mcav_rel, t_hr_rel, hr_1hz)\n",
    "    map_1hz_aligned = np.interp(t_mcav_rel, t_map_rel, map_1hz)\n",
    "\n",
    "    n = min(len(t_mcav_rel), len(mcav_1hz), len(hr_1hz_aligned), len(map_1hz_aligned))\n",
    "\n",
    "    df_1hz = pd.DataFrame({\n",
    "        \"t\": t_mcav_rel[:n],\n",
    "        \"mcav\": mcav_1hz[:n],\n",
    "        \"hr\": hr_1hz_aligned[:n],\n",
    "        \"map\": map_1hz_aligned[:n],\n",
    "    })\n",
    "\n",
    "    df_1hz[\"cvci\"] = df_1hz[\"mcav\"] / df_1hz[\"map\"]\n",
    "\n",
    "    mcav_baseline = mean_in_window(df_1hz, \"mcav\", *BASELINE_WINDOW)\n",
    "    map_baseline = mean_in_window(df_1hz, \"map\", *BASELINE_WINDOW)\n",
    "    cvci_baseline = mcav_baseline / map_baseline if not np.isnan(map_baseline) and map_baseline != 0 else np.nan\n",
    "\n",
    "    max_available_time = float(df_1hz[\"t\"].max())\n",
    "    analysis_end = min(ANALYSIS_WINDOW[1], max_available_time)\n",
    "\n",
    "    response_df = df_1hz[\n",
    "        (df_1hz[\"t\"] >= ANALYSIS_WINDOW[0]) & (df_1hz[\"t\"] <= analysis_end)\n",
    "    ].copy()\n",
    "\n",
    "    if response_df.empty or analysis_end < MIN_RESPONSE_WINDOW_S:\n",
    "        raise ValueError(\"Insufficient response window after alignment.\")\n",
    "\n",
    "    peak_mcav = float(response_df[\"mcav\"].max())\n",
    "    peak_idx = response_df[\"mcav\"].idxmax()\n",
    "    ttp = float(response_df.loc[peak_idx, \"t\"])\n",
    "\n",
    "    map_at_peak = float(response_df.loc[peak_idx, \"map\"])\n",
    "    cvci_peak = peak_mcav / map_at_peak if map_at_peak != 0 else np.nan\n",
    "\n",
    "    delta_mcav_pct = (\n",
    "        ((peak_mcav - mcav_baseline) / mcav_baseline) * 100\n",
    "        if not np.isnan(mcav_baseline) and mcav_baseline != 0\n",
    "        else np.nan\n",
    "    )\n",
    "    delta_map_pct = (\n",
    "        ((map_at_peak - map_baseline) / map_baseline) * 100\n",
    "        if not np.isnan(map_baseline) and map_baseline != 0\n",
    "        else np.nan\n",
    "    )\n",
    "\n",
    "    if np.isnan(cvci_baseline) or cvci_baseline == 0:\n",
    "        delta_cvci_pct = np.nan\n",
    "    else:\n",
    "        delta_cvci_pct = ((cvci_peak - cvci_baseline) / cvci_baseline) * 100\n",
    "\n",
    "    metrics = {\n",
    "        \"baseline_mcav\": mcav_baseline,\n",
    "        \"baseline_map\": map_baseline,\n",
    "        \"baseline_cvci\": cvci_baseline,\n",
    "        \"peak_mcav\": peak_mcav,\n",
    "        \"ttp\": ttp,\n",
    "        \"delta_mcav_pct\": delta_mcav_pct,\n",
    "        \"delta_map_pct\": delta_map_pct,\n",
    "        \"delta_cvci_pct\": delta_cvci_pct,\n",
    "        \"task_start_relative_s\": 0.0,\n",
    "        \"task_end_relative_s\": analysis_end,\n",
    "        \"window_source\": window_source,\n",
    "        \"mcav_channel\": channels[\"mcav\"][\"name\"],\n",
    "        \"hr_channel\": channels[\"hr\"][\"name\"],\n",
    "        \"map_channel\": channels[\"map\"][\"name\"],\n",
    "        \"mat_format\": info[\"type\"],\n",
    "        \"task_start_absolute_s\": start_time_abs,\n",
    "        \"task_end_absolute_s\": end_time_abs,\n",
    "        \"analysis_window_duration_s\": analysis_end,\n",
    "    }\n",
    "\n",
    "    return df_1hz, metrics, comments\n",
    "\n",
    "\n",
    "# =====================================\n",
    "# 6. INDIVIDUAL FIGURES\n",
    "# =====================================\n",
    "\n",
    "def save_panel_figure(df, file_name, analysis_end):\n",
    "    \"\"\"Save 3-panel figure (MCAv, MAP, CVCi) normalized to baseline (%).\"\"\"\n",
    "    clean_name = clean_filename(file_name)\n",
    "    output_path = os.path.join(FIGURES_INDIVIDUAL_PATH, f\"{clean_name}_panels.png\")\n",
    "\n",
    "    mcav_pct = percent_of_baseline(df, \"mcav\")\n",
    "    map_pct = percent_of_baseline(df, \"map\")\n",
    "    cvci_pct = percent_of_baseline(df, \"cvci\")\n",
    "\n",
    "    fig, axs = plt.subplots(3, 1, figsize=(8, 10), sharex=True)\n",
    "\n",
    "    axs[0].plot(df[\"t\"], mcav_pct, linewidth=2)\n",
    "    axs[0].axhline(100, linestyle=\"--\")\n",
    "    axs[0].axvline(0, linestyle=\"--\")\n",
    "    axs[0].axvline(analysis_end, linestyle=\"--\")\n",
    "    axs[0].set_ylabel(\"MCAv (% baseline)\")\n",
    "    axs[0].set_title(file_name)\n",
    "\n",
    "    axs[1].plot(df[\"t\"], map_pct, linewidth=2)\n",
    "    axs[1].axhline(100, linestyle=\"--\")\n",
    "    axs[1].axvline(0, linestyle=\"--\")\n",
    "    axs[1].axvline(analysis_end, linestyle=\"--\")\n",
    "    axs[1].set_ylabel(\"MAP (% baseline)\")\n",
    "\n",
    "    axs[2].plot(df[\"t\"], cvci_pct, linewidth=2)\n",
    "    axs[2].axhline(100, linestyle=\"--\")\n",
    "    axs[2].axvline(0, linestyle=\"--\")\n",
    "    axs[2].axvline(analysis_end, linestyle=\"--\")\n",
    "    axs[2].set_ylabel(\"CVCi (% baseline)\")\n",
    "    axs[2].set_xlabel(\"Time (s)\")\n",
    "\n",
    "    plt.tight_layout()\n",
    "    fig.savefig(output_path, dpi=300, bbox_inches=\"tight\")\n",
    "    plt.close(fig)\n",
    "\n",
    "\n",
    "def save_mcav_ttp_figure(df, file_name, analysis_end):\n",
    "    \"\"\"Save MCAv time-series figure highlighting baseline, task window and TTP.\"\"\"\n",
    "    clean_name = clean_filename(file_name)\n",
    "    output_path = os.path.join(FIGURES_INDIVIDUAL_PATH, f\"{clean_name}_mcav_ttp.png\")\n",
    "\n",
    "    mcav_baseline = mean_in_window(df, \"mcav\", *BASELINE_WINDOW)\n",
    "    response = df[(df[\"t\"] >= 0) & (df[\"t\"] <= analysis_end)].copy()\n",
    "\n",
    "    peak_idx = response[\"mcav\"].idxmax()\n",
    "    peak_mcav = float(response.loc[peak_idx, \"mcav\"])\n",
    "    ttp = float(response.loc[peak_idx, \"t\"])\n",
    "\n",
    "    fig = plt.figure(figsize=(9, 6))\n",
    "\n",
    "    plt.axvspan(-20, 0, alpha=0.15, label=\"Baseline\")\n",
    "    plt.axvspan(0, analysis_end, alpha=0.10, label=\"Task\")\n",
    "    plt.plot(df[\"t\"], df[\"mcav\"], linewidth=2.5, label=\"MCAv\")\n",
    "    plt.axhline(mcav_baseline, linestyle=\"--\", linewidth=1.2, label=\"Baseline MCAv\")\n",
    "    plt.axvline(0, linestyle=\"--\", linewidth=1.2, label=\"Task start\")\n",
    "    plt.axvline(analysis_end, linestyle=\"--\", linewidth=1.2, label=\"Window end\")\n",
    "    plt.axvline(ttp, linestyle=\":\", linewidth=1.8, label=\"TTP\")\n",
    "    plt.scatter([ttp], [peak_mcav], s=80, zorder=5)\n",
    "    plt.text(ttp + 1, peak_mcav, f\"TTP = {ttp:.0f}s\", va=\"bottom\")\n",
    "\n",
    "    plt.xlabel(\"Time (s)\")\n",
    "    plt.ylabel(\"MCAv\")\n",
    "    plt.title(file_name)\n",
    "    plt.legend()\n",
    "    plt.tight_layout()\n",
    "\n",
    "    fig.savefig(output_path, dpi=300, bbox_inches=\"tight\")\n",
    "    plt.close(fig)\n",
    "\n",
    "\n",
    "# =====================================\n",
    "# 7. BATCH PROCESSING\n",
    "# =====================================\n",
    "\n",
    "mat_files = [f for f in os.listdir(DATA_DIR) if f.lower().endswith(\".mat\")]\n",
    "if len(mat_files) == 0:\n",
    "    raise ValueError(\"No .mat files found in DATA_DIR.\")\n",
    "\n",
    "results = []\n",
    "errors = []\n",
    "\n",
    "for file_name in mat_files:\n",
    "    file_path = os.path.join(DATA_DIR, file_name)\n",
    "    group, posture, task = extract_metadata(file_name)\n",
    "\n",
    "    row = {\n",
    "        \"file\": file_name,\n",
    "        \"group\": group,\n",
    "        \"posture\": posture,\n",
    "        \"task\": task,\n",
    "        \"baseline_mcav\": np.nan,\n",
    "        \"baseline_map\": np.nan,\n",
    "        \"baseline_cvci\": np.nan,\n",
    "        \"peak_mcav\": np.nan,\n",
    "        \"ttp\": np.nan,\n",
    "        \"delta_mcav_pct\": np.nan,\n",
    "        \"delta_map_pct\": np.nan,\n",
    "        \"delta_cvci_pct\": np.nan,\n",
    "        \"task_start_relative_s\": np.nan,\n",
    "        \"task_end_relative_s\": np.nan,\n",
    "        \"window_source\": \"\",\n",
    "        \"mcav_channel\": \"\",\n",
    "        \"hr_channel\": \"\",\n",
    "        \"map_channel\": \"\",\n",
    "        \"mat_format\": \"\",\n",
    "        \"task_start_absolute_s\": np.nan,\n",
    "        \"task_end_absolute_s\": np.nan,\n",
    "        \"analysis_window_duration_s\": np.nan,\n",
    "        \"status\": \"ok\",\n",
    "        \"error_message\": \"\",\n",
    "    }\n",
    "\n",
    "    try:\n",
    "        df_1hz, metrics, comments = process_mat_file(file_path, task)\n",
    "        row.update(metrics)\n",
    "\n",
    "        try:\n",
    "            analysis_end = metrics[\"analysis_window_duration_s\"]\n",
    "            save_panel_figure(df_1hz, file_name, analysis_end)\n",
    "            save_mcav_ttp_figure(df_1hz, file_name, analysis_end)\n",
    "        except Exception as fig_error:\n",
    "            print(f\"[FIGURE WARNING] {file_name}: {fig_error}\")\n",
    "\n",
    "    except Exception as e:\n",
    "        row[\"status\"] = \"error\"\n",
    "        row[\"error_message\"] = str(e)\n",
    "\n",
    "        errors.append({\n",
    "            \"file\": file_name,\n",
    "            \"group\": group,\n",
    "            \"posture\": posture,\n",
    "            \"task\": task,\n",
    "            \"error_message\": str(e),\n",
    "        })\n",
    "\n",
    "        print(f\"[ERROR] {file_name}: {e}\")\n",
    "\n",
    "    results.append(row)\n",
    "\n",
    "\n",
    "# =====================================\n",
    "# 8. FINAL TABLES\n",
    "# =====================================\n",
    "\n",
    "df_results = pd.DataFrame(results)\n",
    "df_errors = pd.DataFrame(errors)\n",
    "\n",
    "expected_columns = [\n",
    "    \"file\", \"group\", \"posture\", \"task\",\n",
    "    \"baseline_mcav\", \"baseline_map\", \"baseline_cvci\",\n",
    "    \"peak_mcav\", \"ttp\",\n",
    "    \"delta_mcav_pct\", \"delta_map_pct\", \"delta_cvci_pct\",\n",
    "    \"task_start_relative_s\", \"task_end_relative_s\", \"window_source\",\n",
    "    \"mcav_channel\", \"hr_channel\", \"map_channel\", \"mat_format\",\n",
    "    \"task_start_absolute_s\", \"task_end_absolute_s\", \"analysis_window_duration_s\",\n",
    "    \"status\", \"error_message\"\n",
    "]\n",
    "\n",
    "for col in expected_columns:\n",
    "    if col not in df_results.columns:\n",
    "        df_results[col] = np.nan\n",
    "\n",
    "df_results = df_results[expected_columns]\n",
    "\n",
    "print(\"\\nFinal results table:\")\n",
    "print(df_results.head())\n",
    "\n",
    "if not df_errors.empty:\n",
    "    print(\"\\nFiles with errors:\")\n",
    "    print(df_errors)\n",
    "\n",
    "\n",
    "# =====================================\n",
    "# 9. SAVE OUTPUT TABLES\n",
    "# =====================================\n",
    "\n",
    "results_output_path = os.path.join(OUTPUT_DIR, \"pipeline_results_v8.xlsx\")\n",
    "df_results.to_excel(results_output_path, index=False)\n",
    "\n",
    "if not df_errors.empty:\n",
    "    errors_output_path = os.path.join(OUTPUT_DIR, \"pipeline_errors_v8.xlsx\")\n",
    "    df_errors.to_excel(errors_output_path, index=False)\n",
    "\n",
    "\n",
    "# =====================================\n",
    "# 10. AUTOMATIC SUMMARIES\n",
    "# =====================================\n",
    "\n",
    "df_valid = df_results[df_results[\"status\"] == \"ok\"].copy()\n",
    "\n",
    "if not df_valid.empty:\n",
    "    summary_by_group = (\n",
    "        df_valid.groupby(\"group\")[[\"ttp\", \"delta_mcav_pct\", \"delta_map_pct\", \"delta_cvci_pct\"]]\n",
    "        .agg([\"mean\", \"std\", \"count\"])\n",
    "        .round(2)\n",
    "    )\n",
    "\n",
    "    summary_by_group_task = (\n",
    "        df_valid.groupby([\"group\", \"task\"])[[\"ttp\", \"delta_mcav_pct\", \"delta_map_pct\", \"delta_cvci_pct\"]]\n",
    "        .agg([\"mean\", \"std\", \"count\"])\n",
    "        .round(2)\n",
    "    )\n",
    "\n",
    "    summary_by_group_posture_task = (\n",
    "        df_valid.groupby([\"group\", \"posture\", \"task\"])[[\"ttp\", \"delta_mcav_pct\", \"delta_map_pct\", \"delta_cvci_pct\"]]\n",
    "        .agg([\"mean\", \"std\", \"count\"])\n",
    "        .round(2)\n",
    "    )\n",
    "\n",
    "    summary_by_group.to_excel(os.path.join(OUTPUT_DIR, \"summary_by_group.xlsx\"))\n",
    "    summary_by_group_task.to_excel(os.path.join(OUTPUT_DIR, \"summary_by_group_task.xlsx\"))\n",
    "    summary_by_group_posture_task.to_excel(\n",
    "        os.path.join(OUTPUT_DIR, \"summary_by_group_posture_task.xlsx\")\n",
    "    )\n",
    "\n",
    "    print(\"\\nSummary by group:\")\n",
    "    print(summary_by_group)\n",
    "\n",
    "    print(\"\\nSummary by group and task:\")\n",
    "    print(summary_by_group_task)\n",
    "\n",
    "    print(\"\\nSummary by group, posture, and task:\")\n",
    "    print(summary_by_group_posture_task)\n",
    "\n",
    "\n",
    "# =====================================\n",
    "# 11. SUMMARY FIGURES\n",
    "# =====================================\n",
    "\n",
    "if not df_valid.empty:\n",
    "    df_plot = df_valid.copy()\n",
    "\n",
    "    group_order = [\"CTRL\", \"DP\"]\n",
    "    df_plot[\"group\"] = pd.Categorical(df_plot[\"group\"], categories=group_order, ordered=True)\n",
    "\n",
    "    # Figure 1: TTP by group\n",
    "    fig = plt.figure(figsize=(6, 5))\n",
    "    for i, grp in enumerate(group_order):\n",
    "        values = df_plot[df_plot[\"group\"] == grp][\"ttp\"].dropna().values\n",
    "        if len(values) == 0:\n",
    "            continue\n",
    "        mean = values.mean()\n",
    "        sem = values.std(ddof=1) / np.sqrt(len(values)) if len(values) > 1 else 0\n",
    "        plt.bar(i, mean, yerr=sem, capsize=5)\n",
    "        jitter = np.random.normal(i, 0.04, size=len(values))\n",
    "        plt.scatter(jitter, values, s=40, zorder=3)\n",
    "\n",
    "    plt.xticks([0, 1], group_order)\n",
    "    plt.ylabel(\"TTP (s)\")\n",
    "    plt.title(\"Time-to-Peak by group\")\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(\n",
    "        os.path.join(FIGURES_SUMMARY_PATH, \"ttp_by_group.png\"),\n",
    "        dpi=300,\n",
    "        bbox_inches=\"tight\"\n",
    "    )\n",
    "    plt.close(fig)\n",
    "\n",
    "    # Figure 2: ΔMCAv by group\n",
    "    fig = plt.figure(figsize=(6, 5))\n",
    "    for i, grp in enumerate(group_order):\n",
    "        values = df_plot[df_plot[\"group\"] == grp][\"delta_mcav_pct\"].dropna().values\n",
    "        if len(values) == 0:\n",
    "            continue\n",
    "        mean = values.mean()\n",
    "        sem = values.std(ddof=1) / np.sqrt(len(values)) if len(values) > 1 else 0\n",
    "        plt.bar(i, mean, yerr=sem, capsize=5)\n",
    "        jitter = np.random.normal(i, 0.04, size=len(values))\n",
    "        plt.scatter(jitter, values, s=40, zorder=3)\n",
    "\n",
    "    plt.xticks([0, 1], group_order)\n",
    "    plt.ylabel(\"ΔMCAv (%)\")\n",
    "    plt.title(\"ΔMCAv by group\")\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(\n",
    "        os.path.join(FIGURES_SUMMARY_PATH, \"delta_mcav_by_group.png\"),\n",
    "        dpi=300,\n",
    "        bbox_inches=\"tight\"\n",
    "    )\n",
    "    plt.close(fig)\n",
    "\n",
    "    # Figure 3: TTP by group and task\n",
    "    plot_df = df_plot[df_plot[\"task\"].isin([\"active\", \"passive\"])].copy()\n",
    "    groups = [\"CTRL\", \"DP\"]\n",
    "    tasks = [\"active\", \"passive\"]\n",
    "    x_positions = np.arange(len(tasks))\n",
    "    bar_width = 0.35\n",
    "\n",
    "    fig = plt.figure(figsize=(7, 5))\n",
    "    for j, grp in enumerate(groups):\n",
    "        means = []\n",
    "        sems = []\n",
    "\n",
    "        for task in tasks:\n",
    "            values = plot_df[\n",
    "                (plot_df[\"group\"] == grp) & (plot_df[\"task\"] == task)\n",
    "            ][\"ttp\"].dropna().values\n",
    "\n",
    "            means.append(values.mean() if len(values) else np.nan)\n",
    "            sems.append(values.std(ddof=1) / np.sqrt(len(values)) if len(values) > 1 else 0)\n",
    "\n",
    "        offset = (j - 0.5) * bar_width\n",
    "        plt.bar(x_positions + offset, means, width=bar_width, yerr=sems, capsize=4, label=grp)\n",
    "\n",
    "        for i, task in enumerate(tasks):\n",
    "            values = plot_df[\n",
    "                (plot_df[\"group\"] == grp) & (plot_df[\"task\"] == task)\n",
    "            ][\"ttp\"].dropna().values\n",
    "\n",
    "            jitter = np.random.normal(x_positions[i] + offset, 0.03, size=len(values))\n",
    "            plt.scatter(jitter, values, s=35, zorder=3)\n",
    "\n",
    "    plt.xticks(x_positions, [\"Active\", \"Passive\"])\n",
    "    plt.ylabel(\"TTP (s)\")\n",
    "    plt.title(\"TTP by task and group\")\n",
    "    plt.legend()\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(\n",
    "        os.path.join(FIGURES_SUMMARY_PATH, \"ttp_by_task_and_group.png\"),\n",
    "        dpi=300,\n",
    "        bbox_inches=\"tight\"\n",
    "    )\n",
    "    plt.close(fig)\n",
    "\n",
    "    # Figure 4: Multi-panel paper-style summary\n",
    "    variables = [\n",
    "        (\"delta_mcav_pct\", \"ΔMCAv (%)\", \"A\"),\n",
    "        (\"delta_map_pct\", \"ΔMAP (%)\", \"B\"),\n",
    "        (\"delta_cvci_pct\", \"ΔCVCi (%)\", \"C\"),\n",
    "        (\"ttp\", \"TTP (s)\", \"D\"),\n",
    "    ]\n",
    "\n",
    "    fig, axs = plt.subplots(2, 2, figsize=(10, 8))\n",
    "    axs = axs.flatten()\n",
    "\n",
    "    for ax, (var, ylabel, label) in zip(axs, variables):\n",
    "        grouped = df_plot.groupby(\"group\", observed=True)[var]\n",
    "        mean = grouped.mean().reindex(group_order)\n",
    "        sem = grouped.sem().reindex(group_order)\n",
    "\n",
    "        x = np.arange(len(group_order))\n",
    "        ax.bar(x, mean, yerr=sem, capsize=5, edgecolor=\"black\", linewidth=1.2)\n",
    "\n",
    "        for i, grp in enumerate(group_order):\n",
    "            values = df_plot[df_plot[\"group\"] == grp][var].dropna().values\n",
    "            jitter = np.random.normal(i, 0.05, size=len(values))\n",
    "            ax.scatter(jitter, values, s=45, edgecolors=\"black\", linewidths=0.8, zorder=3)\n",
    "\n",
    "        ax.set_xticks(x)\n",
    "        ax.set_xticklabels(group_order)\n",
    "        ax.set_ylabel(ylabel)\n",
    "        ax.set_title(label, loc=\"left\", fontweight=\"bold\")\n",
    "        ax.spines[\"top\"].set_visible(False)\n",
    "        ax.spines[\"right\"].set_visible(False)\n",
    "\n",
    "    plt.suptitle(\"Cerebrovascular response\", fontsize=14, y=0.98)\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(\n",
    "        os.path.join(FIGURES_SUMMARY_PATH, \"paper_style_panel.png\"),\n",
    "        dpi=300,\n",
    "        bbox_inches=\"tight\"\n",
    "    )\n",
    "    plt.close(fig)\n",
    "\n",
    "\n",
    "# =====================================\n",
    "# 12. FINAL MESSAGES\n",
    "# =====================================\n",
    "\n",
    "print(\"\\nResults saved to:\")\n",
    "print(results_output_path)\n",
    "\n",
    "if not df_errors.empty:\n",
    "    print(\"\\nErrors saved to:\")\n",
    "    print(errors_output_path)\n",
    "\n",
    "print(\"\\nIndividual figures saved to:\")\n",
    "print(FIGURES_INDIVIDUAL_PATH)\n",
    "\n",
    "print(\"\\nSummary figures saved to:\")\n",
    "print(FIGURES_SUMMARY_PATH)\n",
    "\n",
    "print(\"\\nPipeline v8 completed successfully.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d7d96a40-2cc3-4f74-82c7-7546ba32a56a",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
